### ISSUE TITLE
mighty command problem

### ISSUE THREAD

**Issue by Cherryvt** [nbulsi/also#45] opened 2021-05-04 13:52 UTC
Hi all,

May I know how can we check "mighty" command? Or any script suggest to optimize MIG?
Suppose I have an aig circuit, I try to convert it to aig and call "mighty" but there is a core dump.
 also> read_aiger bar.aig
 also> convert --aig_to_mig
 also> mighty
 mig     i/o = 135/128    gates = 3238   level = 14
 Segmentation fault (core dumped)

Any advice or guidance would be greatly appreciated.

Best regards,
Cherry

**Comment by zfchu** [comment] 2021-05-06 03:11
Hi Cherry,

Thanks for reporting the issue. The core dump problem caused by 'depth_view' updated in the mockturtle library.

Now fixed in the master branch.

The current command 'mighty' integrates MIG algebraic rewriting and resubstitution. The command 'cutrw -m' can be used to find additional optimization opportunities. 

also> read_aiger bar.aig
also> convert --aig_to_mig
also> ps -m
MIG   i/o = 135/128   gates = 3238   level = 14
also> mighty
[mighty] ntk   i/o = 135/128   gates = 2749   level = 15
also> cutrw -m
ntk   i/o = 135/128   gates = 2749   level = 15
ntk   i/o = 135/128   gates = 2748   level = 15
also> mighty
[mighty] ntk   i/o = 135/128   gates = 2746   level = 15
also> cutrw -m
ntk   i/o = 135/128   gates = 2746   level = 15
ntk   i/o = 135/128   gates = 2746   level = 15
also> mighty
[mighty] ntk   i/o = 135/128   gates = 2746   level = 15

May it helps.

**Comment by Cherryvt** [comment] 2021-05-08 07:50
Thank you so much for you help. 

By the way, may I know how to keep primary input and output name as the same with original netlist? I saw that when we write out the netlist after doing optimize (using write_verilog -m), the PI and PO names are changed.

May thanks,
Cherry

**Comment by zfchu** [comment] 2021-05-08 08:21
Currently, we cannot support keeping signal names.

But it can be improved in the near future, please refer to [mockturtle](https://github.com/lsils/mockturtle/blob/master/include/mockturtle/views/names_view.hpp) for possible extensions.

Thanks, the issue is hereby closed.

**Closed by zfchu** 2021-05-08 08:21 UTC
